language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO=1.7 STRIPE=127
  - DJANGO=1.7 STRIPE=128
  - DJANGO=1.8 STRIPE=127
  - DJANGO=1.8 STRIPE=128
  - DJANGO=1.9 STRIPE=127
  - DJANGO=1.9 STRIPE=128
  - DJANGO=1.10 STRIPE=127
  - DJANGO=1.10 STRIPE=128
  - DJANGO=1.11 STRIPE=127
  - DJANGO=1.11 STRIPE=128
  - DJANGO=master STRIPE=127
  - DJANGO=master STRIPE=128
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=1.9 STRIPE=127
    - python: "3.3"
      env: DJANGO=1.9 STRIPE=128
    - python: "3.3"
      env: DJANGO=1.10 STRIPE=127
    - python: "3.3"
      env: DJANGO=1.10 STRIPE=128
    - python: "3.3"
      env: DJANGO=1.11 STRIPE=127
    - python: "3.3"
      env: DJANGO=1.11 STRIPE=128
    - python: "2.7"
      env: DJANGO=master STRIPE=127
    - python: "2.7"
      env: DJANGO=master STRIPE=128
    - python: "3.3"
      env: DJANGO=master STRIPE=127
    - python: "3.3"
      env: DJANGO=master STRIPE=128
    - python: "3.5"
      env: DJANGO=1.7 STRIPE=127
    - python: "3.5"
      env: DJANGO=1.7 STRIPE=128
  allow_failures:
    - env: DJANGO=1.11 STRIPE=128
    - env: DJANGO=1.11 STRIPE=127
    - env: DJANGO=master STRIPE=128
    - env: DJANGO=master STRIPE=127
install:
  - pip install tox coveralls
script:
  - tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO-stripe${STRIPE}
after_success:
  - coveralls
notifications:
  slack: pinax:nR1p8bAyjlJUc1CSYn2DT5ps
