language: python
python:
  - "2.7"
env:
  - DJANGO=1.4
  - DJANGO=1.5
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q mock --use-mirrors
  - pip install -q pylint --use-mirrors
  - pip install -q pinax.checkers --use-mirrors
  - pip install -e . --use-mirrors
before_script:
  - "pylint --rcfile=.pylintrc payments"
script:
  - python runtests.py