version: 2.0

common: &common
  working_directory: ~/repo
  steps:
    - checkout
    - restore_cache:
        keys:
          - v3-deps-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - run:
        name: install dependencies
        command: pip install --user tox
    - run:
        name: run tox
        command: ~/.local/bin/tox
    - run:
        name: upload coverage report
        command: |
          if [[ "${TOXENV%-coverage}" != "$TOXENV" ]]; then
            .tox/$TOXENV/bin/coverage xml
            bash <(curl -s https://codecov.io/bash) -Z -X gcov -X coveragepy -X fix -X search -X xcode -f coverage.xml -F $CIRCLE_JOB
          fi
    - save_cache:
        paths:
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
        key: v3-deps-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

jobs:
  lint:
    <<: *common
    docker:
      - image: circleci/python:3.6.1
        environment:
          - TOXENV=checkqa,check_migrated
          - UPLOAD_COVERAGE=0
  py27dj18:
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          TOXENV=py27-dj18-coverage
  py27dj110:
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          TOXENV=py27-dj110-coverage
  py27dj111:
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          TOXENV=py27-dj111-coverage
  py34dj18:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          TOXENV=py34-dj18-coverage
  py34dj110:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          TOXENV=py34-dj110-coverage
  py34dj111:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          TOXENV=py34-dj111-coverage
  py34dj20:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          TOXENV=py34-dj20-coverage
  py35dj18:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          TOXENV=py35-dj18-coverage
  py35dj110:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          TOXENV=py35-dj110-coverage
  py35dj111:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          TOXENV=py35-dj111-coverage
  py35dj20:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          TOXENV=py35-dj20-coverage
  py36dj111:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV=py36-dj111-coverage
  py36dj20:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV=py36-dj20-coverage
  py36dj20psql:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          - TOXENV=py36-dj20-postgres-coverage
          - PINAX_STRIPE_DATABASE_HOST=127.0.0.1
          - PINAX_STRIPE_DATABASE_USER=postgres
          - PINAX_STRIPE_DATABASE_NAME=circle_test
      - image: circleci/postgres:9.6-alpine
  release:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: verify git tag vs. version
          command: |
            if [[ `python setup.py --version` == ${CIRCLE_TAG/v/} ]]; then
              echo "Tag matches version, proceed with the release!";
            else
              echo "Fix version in setup.py and re-tag so they match!"; exit 1
            fi
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create and upload packages
          command: python setup.py sdist bdist_wheel upload

workflows:
  version: 2
  test:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
      - py27dj18:
          filters:
            tags:
              only: /.*/
      - py27dj110:
          filters:
            tags:
              only: /.*/
      - py27dj111:
          filters:
            tags:
              only: /.*/
      - py34dj18:
          filters:
            tags:
              only: /.*/
      - py34dj110:
          filters:
            tags:
              only: /.*/
      - py34dj111:
          filters:
            tags:
              only: /.*/
      - py34dj20:
          filters:
            tags:
              only: /.*/
      - py35dj18:
          filters:
            tags:
              only: /.*/
      - py35dj110:
          filters:
            tags:
              only: /.*/
      - py35dj111:
          filters:
            tags:
              only: /.*/
      - py35dj20:
          filters:
            tags:
              only: /.*/
      - py36dj111:
          filters:
            tags:
              only: /.*/
      - py36dj20:
          filters:
            tags:
              only: /.*/
      - py36dj20psql:
          filters:
            tags:
              only: /.*/
      - release:
          context: org-global
          requires:
            - lint
            - py27dj18
            - py27dj110
            - py27dj111
            - py34dj18
            - py34dj110
            - py34dj111
            - py34dj20
            - py35dj18
            - py35dj110
            - py35dj111
            - py35dj20
            - py36dj111
            - py36dj20
            - py36dj20psql
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
