version: 2.0

common: &common
  working_directory: ~/repo
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-deps-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}
          - v1-deps-
    - run:
        name: install dependencies
        command: pip install --user $DJANGO coverage codecov
    - run:
        name: run tests
        command: PATH=~/.local/bin:$PATH coverage run setup.py test
    - save_cache:
        paths:
          - ~/.local
          - ./eggs
        key: v1-deps-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}
    - run:
        name: upload coverage results
        command: PATH=~/.local/bin:$PATH codecov --required --flags $CIRCLE_JOB

jobs:
  lint:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-lint-deps-{{ checksum "tox.ini" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8==3.4.1 flake8-quotes==0.11.0 isort==4.2.15
      - save_cache:
          paths:
            - ./venv
          key: v3-lint-deps-{{ checksum "tox.ini" }}
      - run:
          name: lint code
          command: |
            . venv/bin/activate
            flake8 pinax
      - run:
          name: check imports
          command: |
            . venv/bin/activate
            isort --recursive --check-only --diff pinax -sp tox.ini

  py27dj18:
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          DJANGO=Django>=1.8,<1.9
  py27dj19:
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          DJANGO=Django>=1.9,<1.10
  py27dj110:
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          DJANGO=Django>=1.10,<1.11
  py27dj111:
    <<: *common
    docker:
      - image: circleci/python:2.7
        environment:
          DJANGO=Django>=1.11,<2.0
  py33dj18:
    <<: *common
    docker:
      - image: circleci/python:3.3
        environment:
          DJANGO=Django>=1.8,<1.9
  py34dj18:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          DJANGO=Django>=1.8,<1.9
  py34dj19:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          DJANGO=Django>=1.9,<1.10
  py34dj110:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          DJANGO=Django>=1.10,<1.11
  py34dj111:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          DJANGO=Django>=1.11,<2.0
  py34djmaster:
    <<: *common
    docker:
      - image: circleci/python:3.4
        environment:
          DJANGO=https://github.com/django/django/tarball/master
  py35dj18:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          DJANGO=Django>=1.8,<1.9
  py35dj19:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          DJANGO=Django>=1.9,<1.10
  py35dj110:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          DJANGO=Django>=1.10,<1.11
  py35dj111:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          DJANGO=Django>=1.11,<2.0
  py35djmaster:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          DJANGO=https://github.com/django/django/tarball/master
  py36dj111:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          DJANGO=Django>=1.11,<2.0
  py36djmaster:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          DJANGO=https://github.com/django/django/tarball/master

workflows:
  version: 2
  lint-and-test:
    jobs:
      - lint
      - py27dj18:
          requires:
            - lint
      - py27dj19:
          requires:
            - lint
      - py27dj110:
          requires:
            - lint
      - py27dj111:
          requires:
            - lint
      - py33dj18:
          requires:
            - lint
      - py34dj18:
          requires:
            - lint
      - py34dj19:
          requires:
            - lint
      - py34dj110:
          requires:
            - lint
      - py34dj111:
          requires:
            - lint
      # Failing to start Django Tests for some reason
      # - py34djmaster:
      #     requires:
      #       - lint
      - py35dj18:
          requires:
            - lint
      - py35dj19:
          requires:
            - lint
      - py35dj110:
          requires:
            - lint
      - py35dj111:
          requires:
            - lint
      - py35djmaster:
          requires:
            - lint
      - py36dj111:
          requires:
            - lint
      - py36djmaster:
          requires:
            - lint
